### ISSUE TITLE
Map is not shown - but google is shown in the left bottom

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-maps#12]
I have followed the instructions in this Example of this repo. Upon opening the app, i am able to see a map area with google at the left bottom. But there is no map appearing (but a yellowish grey layer shown)

Please kindly help me.

**Comment by mpost** [comment]
I presume you are using Android? You have to specify the API key as pointed out in the README: https://github.com/eclipsesource/tabris-plugin-maps#android

**Comment by natanraj** [comment]
Yes,Mpost. I got it from console.google.com and attached the keystore SHA1 keys as well.

**Comment by mpost** [comment]
attached in what way?

**Comment by natanraj** [comment]
I have a keystore file using which i got the SHA1 keys.
Then in console.google.com, i got a android API key and attached the package of my app and the SHA1. The API key is now set up in config.xml as below

``` xml
<plugin name="tabris-plugin-maps" spec="2.0.1" >
  <variable name="ANDROID_API_KEY" value="mykeyfromgoogle" />
</plugin>
```

And using Cloud build....Am I missing something.

**Comment by mpost** [comment]
that is actually correct. it can take a few minutes until the api key is enabled on the google side. Also kill the app on the device an relaunch seams to re-enforce a recheck of the api key.

**Comment by natanraj** [comment]
Yeah. i waited almost 2 hours. and now even killed the existing app .. Same results.. :-(

**Comment by mpost** [comment]
Have you added the [build hook](https://github.com/eclipsesource/tabris-plugin-maps/blob/master/example/hooks/api_key_hook.js) to copy the `ANDROID_API_KEY` into the plugin?

**Comment by natanraj** [comment]
mh. interesting. I didn't .... Let me try that route

**Comment by mpost** [comment]
Actually the build hook is used to place an API key given on the command line via `cordova plugin add ...` into the `<variable name="ANDROID_API_KEY" value="mykeyfromgoogle" />` tag.

Since you are using it directly you should not need the hook. The hook though has a bug that will overwrite an existing key with undefined even if no arg is given. We will fix that.

**Comment by natanraj** [comment]
Yeah. I dont think that is resolving the problem though.  Still the map layers not shown

**Comment by mpost** [comment]
To see if your key ended up in the app correctly you can open the created apk in AndroidStudio (drag and drop onto it in latest beta version) and see if the AndroidManifest.xml has an entry

``` xml
        <meta-data
            android:name="com.google.android.maps.v2.API_KEY"
            android:value="your api key here" />
```

**Comment by natanraj** [comment]
sure . will try tomorrow..

**Comment by mpost** [comment]
Great let us know what the outcome is.

**Comment by natanraj** [comment]
API Key info is there in the manifest file.

**Comment by mpost** [comment]
That is promissing... The cloud build currently uses an internal debug keystore when building in debug mode. Please make sure to build a release version (or add the sha1 from the build apk in the google dev console).

The behavior of the build service will change in the future but for now when debugging is enabled a different signing key is used everytime.

**Comment by natanraj** [comment]
hey. atlast i found the rootcause. Unfortunately i have been having two config.xml files :-(. One in my root folder and another in my cordova folder. I had been updating the root folder which is not picked during build, but inside the cordova folder. Once i changed the right cordova folder's config.xml, the map came so beautifully.

Thanks for all the patience.

**Comment by mpost** [comment]
Great to hear that you could find the cause. :)

**Comment by natanraj** [comment]
hi.. I am sorry to reopen this issue. I am again getting the same problem though now I have the right cordova folder updated etc. What are the other possible scenarios one will get grey empty map (but with google shown in the bottom) ?

 <plugin name="tabris-plugin-maps" spec="2.0.1" >
        <variable name="ANDROID_API_KEY" value="myKeyFromGoogleDevConsoleSteps" />
    </plugin>

**Comment by cookieguru** [comment]
What do you see in logcat?

**Comment by natanraj** [comment]
oh. Yeah. I am trying this in my own Developer Debug App with My ScratchPad.

**Comment by natanraj** [comment]
@cookieguru Unfortunately i couldn't get ADB driver for my xiaomi driver and never tried adb logcat..

**Comment by cookieguru** [comment]
@natanraj Try one of [these](https://play.google.com/store/search?q=logcat&c=apps&docType=1)

**Comment by natanraj** [comment]
my app name is com.mydomain.firstApp..

`adb logcat com.mydomain.firstApp:I *:S`   will this give right log ? I am not seeing anything printed...so just checking. Without that *:S.. it gives all log which keeps running..

**Comment by natanraj** [comment]
using adb logcat | find "com.mydomain.firstApp" - i got the below.
`E/Vold    (  429): Failed to find mounted volume for /storage/sdcard1/Android/data/com.mydomain.firstApp/cache/
W/ContextImpl(28991): Failed to ensure directory: /storage/sdcard1/Android/data/com.mydomain.firstApp/cache
E/Google Maps Android API(28991):       Android Application (<cert_fingerprint>;<package_name>): 7D:E2:A6:43:90:FF:97:1A
:B4:FB:2F:88:7B:B2:0B:B3:8B:1C:8A:28;com.mydomain.firstApp
E/DynamiteModule(28991): Failed to load DynamiteLoader: java.lang.ClassNotFoundException: Didn't find class "com.google.
android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader" on path: DexPathList[[zip file "/data/app/com.mydomain.fi
rstApp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mydomain.firstApp-1/lib/arm, /vendor/lib, /system/lib]]`

I am running this on Developer App version of my app.. Am i not having any permissions ?

**Comment by mpost** [comment]
Most likely scenario of the greyish screen is that you don't have the correct api key in your app. Is it correctly placed in the apk and matches the signing key you use for your app?

**Comment by mpost** [comment]
The exception you posted above looks untypical. Not sure where that originates from. is your project publicly available on github?

**Comment by natanraj** [comment]
yes. @mpost

**Comment by natanraj** [comment]
@mpost  Please hold on. I guess i used different Development signing keys in the Build Page. I am getting corresponding API Key for it and trying with this. If it doesn't still resolve i will seek your help.

**Comment by natanraj** [comment]
Hey. I found it is working now. Looks like when i toggled my release app to Dev app, i didn't  ensure the signing key - API key combination. It works now....

**Comment by maxapps** [comment]
I finally got this working with help from @cookieguru and am including detailed steps here in case there are others who might not be familiar with the specific steps needed to use the Google Maps API with Tabris. My confusion was caused by previous experience using the map APIs from javascript and confusing some of the terms in the documentation.

Basically, you just have to enable the Android API from the Google API console. This seems pretty obvious in retrospect but I misunderstood and thought it had something to do with changing the **restriction** settings for the API.

## Enable Android for the Google Project
**NOTE:** The screenshots below might not exactly match what you see. I have several different Google projects and the steps were not identical on all of them.
1. Go to the main page for the Google project which has the API Key you intend to use. For me, this was `https://console.cloud.google.com/home/dashboard?project={myproject}`.

2. Click **APIs & Services** in the left menu then select **Dashboard**. 
![ss01](https://user-images.githubusercontent.com/292808/41192443-f54de272-6bfd-11e8-81fc-5d29fafff905.png)

3. From the Dashboard page, click the **ENABLE APIS AND SERVICES** button at the top of the page. 
![ss02](https://user-images.githubusercontent.com/292808/41192452-25acb2e0-6bfe-11e8-93d8-845dbfd8adbe.png)
4. From the API Library page, click the box for **Maps SDK for Android**. 
![ss03](https://user-images.githubusercontent.com/292808/41192468-580b0f5c-6bfe-11e8-9fae-1dd0bbe77efe.png)
5. After the page loads, find the section labeled **Maps SDK for Android** and click the **ENABLE** button. 
![ss04](https://user-images.githubusercontent.com/292808/41192479-8cc80cfe-6bfe-11e8-9eeb-32d2d4165330.png)

This is what worked for me. Other than the steps above, you simply copy the Google API Key from the Google console into the **General - Environment Variables** section of the Tabris settings page for your app.

**Comment by mpost** [comment]
@maxapps Thanks for the detailed information. This should be helpful for other people. 👍
