### ISSUE TITLE
Map fails on enabling showMyLocation true

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-maps#18]
The below code was working few weeks back, but fails now

`var map = new esmaps.Map({
    left: 0, right: 0, top: 0, bottom: 80
  }).on('ready', function() {
   	this.set('showMyLocation', true);})`
Has something got updated recently with tabris ? I am using tabris-maps.2.0.1 spec and cloud build

it throws - 'Could not set properties on com.eclipsesource.maps.Map (Reason: android.permission.ACCESS_FINE_LOCATION not available)'

**Comment by cookieguru** [comment]
Based on the error it looks like you have the Location permission disallowed for the app on the device.  Can you [check to see if you have the Location permission enabled](http://www.howtogeek.com/230683/how-to-manage-app-permissions-on-android-6.0/)?

**Comment by natanraj** [comment]
You are right. I should have checked this first. Thanks...

**Comment by cookieguru** [comment]
Question since I haven't tested this myself: Does it throw an `Error` on the JS side or something else?  If an `Error` it would be nice if the [`IllegalStateException`](https://github.com/eclipsesource/tabris-plugin-maps/blob/dd02fd44c520b33c9517f932c102c48cbac891f9/src/android/com/eclipsesource/tabris/maps/MapPropertyHandler.java#L130) could get thrown as something other than an `Error` on the JS side.  Right now the only way to differentiate this from other errors is by checking for the specific hardcoded message and presumably you'd want to handle this differently than say an unset property error.

**Comment by mpost** [comment]
You could use a plugin like https://www.npmjs.com/package/cordova.plugins.diagnostic to check if the permission is available and react accordingly.

**Comment by cookieguru** [comment]
Sometimes I underestimate the Cordova community.  That's a great solution @mpost
